# Use absolute path to existing CLIF data
data_home: /home/code/clif-multimodal-fm-protoecg/data
processed_data_home: /home/kajch/multi-modal-protoecg-gem/cocoa/data/processed

collation_config: /home/kajch/multi-modal-protoecg-gem/cocoa/config/collation/clif-v2.1.yaml
tokenization_config: /home/kajch/multi-modal-protoecg-gem/cocoa/config/tokenization/clif-21.yaml